language: php
php:
  - 7.2

mysql:
  database: recipes_book
  username: root
  encoding: utf8


before_script:
  - mysql -e "source db.sql"
  - composer install

script:
  - mkdir logs

after_script:
  - php vendor/bin/coveralls -v
